name: chat_composer
description: A Flutter package for easy implementation of chat composer.
version: 1.0.1
homepage: https://github.com/anokabb/chat_composer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.8
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  meta: ^1.7.0
  flutter_sound_lite: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - packages/chat_composer/images/delete_icon.png
