name: chat_composer
description: A Flutter package for easy implementation of chat composer.
version: 0.0.1
homepage: https://github.com/anokabb/chat_composer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_audio_recorder2: ^0.0.2
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3
  fluttertoast: ^8.0.8
  path_provider: ^2.0.6
  permission_handler: ^8.2.6
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - packages/chat_composer/images/delete_icon.png
